# Generated by Django 4.1 on 2022-08-17 11:39

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            (1, "KYC onboarding"),
                            (2, "Funding features"),
                            (3, "Trading features"),
                            (4, "Custody features"),
                            (5, "Fee schedule"),
                            (6, "Security"),
                            (7, "Others"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "country",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            (1, "China"),
                            (2, "Singapore"),
                            (3, "United Kingdom"),
                            (4, "United States"),
                        ],
                        max_length=1,
                    ),
                ),
                ("question", models.CharField(max_length=200)),
            ],
        ),
    ]
