# Generated by Django 4.1 on 2022-08-17 15:11

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("chatbotFAQ", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="country",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("China", "China"),
                    ("Singapore", "Singapore"),
                    ("United Kingdom", "United Kingdom"),
                    ("United States", "United States"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator("[+-/%]", inverse_match=True)
                ],
            ),
        ),
    ]
